// Find
	DRAGON_HEART_VNUM = 100000,
};

#endif /* __INC_METIN2_UNIQUE_ITEM_H */

// Add Under
#ifdef OFFICIAL_LEADER_BOOK_PLUS
	UNIQUE_ITEM_PARTY_BONUS_EXP_GOLD = 72059,
	UNIQUE_ITEM_PARTY_BONUS_EXP_MALL_GOLD = 72060,
#endif
